---
http:
  addr: :9090
  # http请求超时，单位秒
  timeout: 10
jwt:
  secret: secret
  # jwt token过期时间，单位秒
  expire: 7200
mysql:
  url: root:123456@tcp(127.0.0.1:3306)/ohmydata?charset=utf8&parseTime=True&loc=Local
redis:
  addr: 127.0.0.1:6379
  db: 0
  password: ""
